sudo: false
language: python
cache: pip
python:
    - "2.7"
    - "3.4"
install:
    - "pip install -r testing-requirements.txt"
# command to run tests
script: lettuce --tag=-not_working Lettuce_Tests
